import type { Exporter } from './exporter';
import type { World, Room, Property, Direction } from '../model/world';
import { roomName } from '../model/world';

// The Beguile exporter — diorama's first target.
//
// NOTE: the exact room/exit API is still settling in the Beguile IF standard
// library (bglStdLib). This emitter produces a clean, readable first cut — rooms
// as objects with a description and directional exits, things nested inside — and
// is the single place to update when that world model firms up.

const DIR_PROP: Record<Direction, string> = {
  n: 'n_to', s: 's_to', e: 'e_to', w: 'w_to',
  ne: 'ne_to', nw: 'nw_to', se: 'se_to', sw: 'sw_to',
  u: 'u_to', d: 'd_to', in: 'in_to', out: 'out_to',
};

function ident(name: string, fallback: string): string {
  const id = name.trim().replace(/[^A-Za-z0-9_]+/g, '_').replace(/^(\d)/, '_$1');
  return id.length ? id : fallback;
}

function quote(s: string): string {
  // Beguile strings use I6 conventions: ~ for a literal double-quote, ^ for newline.
  return '"' + s.replace(/"/g, '~').replace(/\n/g, '^') + '"';
}

function emitProperty(p: Property): string {
  if (typeof p.value === 'boolean') return p.value ? `    ${p.key};` : '';
  if (typeof p.value === 'number') return `    ${p.key} = ${p.value};`;
  return `    ${p.key} = ${quote(p.value)};`;
}

function emitRoom(room: Room, idOf: (id: string) => string): string {
  const lines: string[] = [`worldObject ${idOf(room.id)} {`];
  if (room.type && room.type !== 'object') lines.push(`    // kind: ${room.type}`);
  if (room.parent) lines.push(`    // parent: ${idOf(room.parent)}`);
  for (const p of room.properties) {
    const line = emitProperty(p);
    if (line) lines.push(line);
  }
  for (const exit of room.exits) {
    const prop = exit.dir ? DIR_PROP[exit.dir] : undefined;
    if (prop) lines.push(`    ${prop} = ${idOf(exit.to)};`);
    else lines.push(`    // exit → ${idOf(exit.to)} (no direction assigned yet)`);
  }
  for (const thing of room.things) {
    lines.push(`    // TODO: object "${thing.name}" staged here`);
  }
  lines.push('}');
  return lines.join('\n');
}

export const beguileExporter: Exporter = {
  id: 'beguile',
  label: 'Beguile',
  extension: '.bgl',

  export(world: World): string {
    // Map each room id to a unique Beguile identifier derived from its name.
    const used = new Set<string>();
    const idMap = new Map<string, string>();
    for (const room of world.rooms) {
      let base = ident(room.name, `room_${idMap.size + 1}`);
      let name = base, n = 1;
      while (used.has(name)) name = `${base}_${++n}`;
      used.add(name);
      idMap.set(room.id, name);
    }
    const idOf = (id: string) => idMap.get(id) ?? ident(roomName(world, id), id);

    const header = `// ${world.name} — generated by diorama\n// Target: Beguile (github.com/onyxring/beguiler)\n`;
    const body = world.rooms.map(r => emitRoom(r, idOf)).join('\n\n');
    const start = world.start ? `\n// Starting room: ${idOf(world.start)}\n` : '\n';
    return `${header}\n${body}\n${start}`;
  },
};
