import type { Exporter } from './exporter';
import type { World, Room, Property, Direction } from '../model/world';
import { roomName, propType, isArrayType } from '../model/world';

// The Beguile exporter — diorama's first target.
//
// Emits each object as a Beguile declaration `<type> <id> { … }`, where the object's TYPE is
// the class (object, thing, room, …). Those classes come from the Beguile standard library /
// your own definitions — this file only generates the world data. Properties carry Beguile
// type declarations (string/int/array<dictionaryWord>/…), booleans become I6 attributes, and
// directional exits use the standard-library `<dir>_to` notation.

const DIR_PROP: Record<Direction, string> = {
  n: 'n_to', s: 's_to', e: 'e_to', w: 'w_to',
  ne: 'ne_to', nw: 'nw_to', se: 'se_to', sw: 'sw_to',
  u: 'u_to', d: 'd_to', in: 'in_to', out: 'out_to',
};

// Boolean flags that are I6 attributes → collected into `attributes = { … }`. Other booleans
// are emitted as `bool key = …;` properties.
const I6_ATTRIBUTES = new Set([
  'light', 'container', 'supporter', 'openable', 'open', 'lockable', 'locked', 'on',
  'switchable', 'static', 'scenery', 'concealed', 'edible', 'enterable', 'animate',
  'transparent', 'clothing', 'worn', 'proper', 'pluralname', 'male', 'female', 'neuter', 'absent',
]);

function ident(name: string, fallback: string): string {
  const id = name.trim().replace(/[^A-Za-z0-9_]+/g, '_').replace(/^(\d)/, '_$1');
  return id.length ? id : fallback;
}

function quote(s: string): string {
  // Beguile strings use I6 conventions: ~ for a literal double-quote, ^ for newline.
  return '"' + s.replace(/"/g, '~').replace(/\n/g, '^') + '"';
}

function emitProperty(p: Property): string {
  const type = propType(p);
  const v = p.value;
  if (type === 'bool') return `    bool ${p.key} = ${v === true ? 'true' : 'false'};`;
  if (type === 'int' || type === 'uint' || type === 'float') {
    const n = typeof v === 'number' ? v : (type === 'float' ? parseFloat(String(v)) : parseInt(String(v), 10));
    return Number.isFinite(n) ? `    ${type} ${p.key} = ${n};` : '';
  }
  if (type === 'dictionaryWord') {
    const w = String(Array.isArray(v) ? (v[0] ?? '') : v).trim();
    return w ? `    dictionaryWord ${p.key} = .${w};` : '';
  }
  if (isArrayType(type)) {
    const arr = Array.isArray(v) ? v : String(v ?? '').split(/[,\n]/).map(s => s.trim()).filter(Boolean);
    if (!arr.length) return '';
    const elems = type === 'array<dictionaryWord>' ? arr.map(w => '.' + String(w).trim())
      : type === 'array<int>' ? arr.map(x => String(parseInt(String(x), 10) || 0))
      : arr.map(x => quote(String(x)));
    return `    ${type} ${p.key} = {${elems.join(', ')}};`;
  }
  return v ? `    string ${p.key} = ${quote(String(v))};` : '';   // string
}

function emitRoom(room: Room, idOf: (id: string) => string): string {
  const type = (room.type || 'object').trim() || 'object';
  const lines: string[] = [`${type} ${idOf(room.id)} {`];
  if (room.parent) lines.push(`    parent = ${idOf(room.parent)};`);

  // Boolean attributes → one `attributes = { … }` line; other properties emitted individually.
  const attrs: string[] = [];
  for (const p of room.properties) {
    if (propType(p) === 'bool' && p.value === true && I6_ATTRIBUTES.has(p.key.trim().toLowerCase())) {
      attrs.push(p.key);
    }
  }
  if (attrs.length) lines.push(`    attributes = {${attrs.join(', ')}};`);

  for (const p of room.properties) {
    if (propType(p) === 'bool' && p.value === true && I6_ATTRIBUTES.has(p.key.trim().toLowerCase())) continue;
    const line = emitProperty(p);
    if (line) lines.push(line);
  }

  for (const exit of room.exits) {
    const prop = exit.dir ? DIR_PROP[exit.dir] : undefined;
    if (prop) lines.push(`    ${prop} = ${idOf(exit.to)};`);
    else lines.push(`    // exit → ${idOf(exit.to)} (no direction assigned yet)`);
  }
  for (const thing of room.things) {
    lines.push(`    // TODO: object "${thing.name}" staged here`);
  }
  lines.push('}');
  return lines.join('\n');
}

export const beguileExporter: Exporter = {
  id: 'beguile',
  label: 'Beguile',
  extension: '.bgl',

  export(world: World): string {
    // Map each room id to a unique Beguile identifier derived from its name.
    const used = new Set<string>();
    const idMap = new Map<string, string>();
    for (const room of world.rooms) {
      let base = ident(room.name, `room_${idMap.size + 1}`);
      let name = base, n = 1;
      while (used.has(name)) name = `${base}_${++n}`;
      used.add(name);
      idMap.set(room.id, name);
    }
    const idOf = (id: string) => idMap.get(id) ?? ident(roomName(world, id), id);

    const header = `// ${world.name} — generated by diorama\n// Target: Beguile (github.com/onyxring/beguiler)\n`;
    const body = world.rooms.map(r => emitRoom(r, idOf)).join('\n\n');
    return `${header}\n${body}\n`;
  },
};
